install: |-
  pdd --file=/dev/null
assets:
  secring.gpg: yegor256/home#assets/secring.gpg
  pubring.gpg: yegor256/home#assets/pubring.gpg
  settings.xml: yegor256/home#assets/jcabi/settings.xml
merge:
  script: |-
    mvn clean install -Pqulice --errors --settings ../settings.xml
deploy:
  script: |-
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pqulice -Psonatype -Pjcabi --errors --settings ../settings.xml
    mvn clean site-deploy -Psite --errors --settings ../settings.xml
